### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by hawkoon** [ECHibiki/Kissu-Vi#113]
Trying to open install.php gives this error in the server logs:

> PHP Fatal error:  Uncaught Exception: Template file 'error.html' does not exist or is empty in ''! in /var/www/html/inc/template.php:74\nStack trace:\n#0 /var/www/html/inc/display.php(128): Element('error.html', Array)\n#1 /var/www/html/inc/functions.php(365): error('Caught fatal er...', 3)\n#2 [internal function]: fatal_error_handler()\n#3 {main}\n  thrown in /var/www/html/inc/template.php on line 74

**Comment by ECHibiki** [comment]
The instance-config.php file is missing

Thought I fixed that in the release but it seems I didn't. Will add that in with a few quick fixes I did on the main site

**Comment by ECHibiki** [comment]
https://github.com/ECHibiki/Kissu-Vi/releases/tag/V6.1.1
This version isn't identical to what's running on kissu.moe though everything that exists there should work here.

various extras that are used with the project are listed here and should be installed independently if wanted https://github.com/ECHibiki/Kissu
Of particular use is
https://github.com/ECHibiki/captchouli and https://github.com/ECHibiki/Community-Banners/tree/cf0e73dfe3cfda7de5e670858875561ad8d7ccd6
while https://github.com/ECHibiki/Kissu-React/ is an in progress upgrade of the experimental React UI in V6.1.1
